import Head from "next/head";

import Layout from "../components/Layout";
import Section1 from "../components/Home/section1";
import Section2 from "../components/Home/section2";
import Section21 from "../components/Home/section21";
import Section3 from "../components/Home/section3";
import Section4 from "../components/Home/section4";
import Section5 from "../components/Home/section5";
import Section6 from "../components/Home/section6";
import Section7 from "src/components/Home/section7";
import Section8 from "src/components/Home/section8";
import { Divider } from "@mui/material";
import { getSession, useSession } from "next-auth/react";
import { useRouter } from "next/router";
import { useEffect } from "react";
import Ripple from "src/components/Home/ripple";
import { useState } from "react";
import PropagateLoader from "react-spinners/PropagateLoader";

// const override: CSSProperties = {
//   display: "block",
//   margin: "0 auto",
//   borderColor: "red",
// };
const Home = (props) => {
  let [loading, setLoading] = useState(false);
  let [color, setColor] = useState("#ffffff");
  const router = useRouter();

  useEffect(() => {
    setLoading(true)
    setTimeout(() => {
      setLoading(false);
    }, 5000);

    if (props?.user?.firstname) {
      router.push("/dashboard");
    }
  },[] );

  return (
    <Layout>
    <div className="container">
      <Head>
        <title>Staybusy.io</title>
        <meta name="description"
content="Generated by create next app" />
        <link rel="icon"
href="/favicon.ico" />
      </Head>
      {
        loading?  <div className="container1">  <PropagateLoader
        color={'#FFCC00'}
        loading={loading}

        size={20}
        aria-label="Loading Spinner"
        data-testid="loader"
      />

</div>
       :<>
      <div className="number1">
      <Section1 />
      </div>
      <Ripple />
      <div className="sectionColor"><Section2 />

      <Section3 />
      <Section21 />
      <Section6 />
      <Section4 />
      </div>

      <Section7 />
      <Divider style={{color:"#E4E4E7"}} />


      <Section8 />
      <Section5 />

      </>
      }

     </div>
  </Layout>
  );
};

export default Home;

export async function getServerSideProps(ctx) {
  const session = await getSession(ctx);

  if (session) {
    return {
      redirect: {
        destination: "/dashboard",
        permanent: false,
      },
    };
  }

  return {
    props: {
      ...session,
    },
  };
}
